/**
 * Long-form, unique content for each tool page to meet quality and minimum content guidelines.
 * Each block is 200+ words of substantive, useful information.
 */

export const TOOL_PAGE_CONTENT: Record<string, { title: string; body: string }> = {
  'sha-256': {
    title: 'About SHA-256 Hash Generator',
    body: `SHA-256 (Secure Hash Algorithm 256-bit) is a cryptographic hash function that produces a fixed 256-bit (32-byte) hash value. It is widely used for data integrity checks, digital signatures, and security applications. This tool runs entirely in your browser—no data is sent to any server, so your input stays private.

**Common use cases:** Verify file integrity by comparing hashes before and after download. Check password or token hashes in development. Generate checksums for API payloads or configuration files. Create deterministic identifiers from strings (e.g., cache keys or unique IDs). Many version control and backup systems use SHA-256 to detect changes.

**How it works:** You paste or type any text; the tool computes the SHA-256 hash instantly and displays it in hexadecimal. The output is always 64 hex characters long, regardless of input size. Even a tiny change in the input produces a completely different hash, which makes it ideal for detecting tampering or corruption.

**Tips:** Use "Compare" or copy both hashes to verify two inputs match. For files, use a dedicated checksum utility; this tool is best for short text and quick checks. Never use raw SHA-256 alone for storing passwords—use proper key derivation (e.g., bcrypt or Argon2) in production.`,
  },
  'json-beautifier': {
    title: 'About the JSON Beautifier & Validator',
    body: `JSON (JavaScript Object Notation) is the standard format for APIs, config files, and data exchange. Minified JSON is hard to read and debug; this tool formats it with indentation and line breaks. It also validates syntax and can fix common mistakes like missing commas or trailing commas, so you spend less time hunting errors.

**When to use it:** Pretty-print API responses or log output for readability. Minify JSON to reduce payload size for production. Validate JSON before sending it to a backend or storing it. Repair JSON that was hand-edited or generated by tools that produced invalid syntax. Quickly inspect nested structures without opening a full IDE.

**How it works:** Paste your JSON into the input area. The tool parses it and, if valid, shows formatted (beautified) or minified output. If there are recoverable errors, the auto-fix engine attempts repairs—e.g., adding missing commas or removing trailing commas where the parser allows. Invalid JSON is clearly reported with error messages to help you correct the source.

**Best practices:** For large documents, consider splitting or validating in chunks. Always validate JSON from untrusted sources before using it in your app. This tool processes data locally; nothing is uploaded to external servers, so sensitive configuration or payloads remain on your device.`,
  },
  'base64-text': {
    title: 'About Base64 Encode & Decode (Text)',
    body: `Base64 encoding converts binary data into ASCII text using a set of 64 characters (A–Z, a–z, 0–9, plus two symbols). It is commonly used to embed binary data in JSON, XML, or URLs, and for basic obfuscation (not encryption). This utility encodes and decodes text in the browser with no server round-trips.

**Typical uses:** Encode credentials or tokens for HTTP Basic Auth headers. Embed small data payloads in JSON or config without binary blobs. Decode API responses or webhooks that return Base64. Test encoding/decoding in development or documentation. Sanitize or inspect Base64 strings before sending them to backend services.

**How it works:** Enter plain text to get Base64, or paste Base64 to get the original text. Encoding increases size by about 33%; the tool can show the expansion ratio so you know the overhead. Decoding validates the input and reports errors if the string is not valid Base64. All processing happens in your browser—your text is never sent elsewhere.

**Notes:** Base64 is not encryption; anyone can decode it. Do not use it to protect secrets. For URLs, consider URL-safe Base64 variants if your system requires them. For large files, use a dedicated file-based encoder; this page is optimized for text and short strings.`,
  },
  'base64-image': {
    title: 'About Base64 Image Encoder & Decoder',
    body: `Base64 image encoding turns image files into a long text string (a Data URI). That string can be embedded in HTML, CSS, or JSON, so you can display images without a separate file request. Decoding does the reverse: paste a Base64 image string and recover or preview the image. Everything runs locally in your browser for privacy and speed.

**Use cases:** Embed small icons or thumbnails in HTML or CSS to reduce HTTP requests. Include images in JSON APIs or config (e.g., app icons or badges). Test Data URIs in development. Decode and preview Base64 images from APIs or documentation. Generate inline images for email templates or single-file demos.

**How it works:** For encoding, upload an image (or drag and drop); the tool converts it to a Base64 Data URI and optionally shows the string length and approximate size impact. For decoding, paste a Base64 or full Data URI string; the tool validates it and displays the image. Large images produce long strings—embedding huge files in code is usually not recommended; this tool is best for small assets.

**Privacy and performance:** All conversion is done in your browser. No images are uploaded to any server. Keep in mind that Base64 increases size by roughly 33%, so use it where the trade-off (fewer requests, single-file portability) is worth it.`,
  },
  'tic-tac-toe': {
    title: 'About the Tic Tac Toe Game',
    body: `This is a classic Tic Tac Toe (Noughts and Crosses) game built for the web. You can play against a friend on the same device or challenge the built-in AI. The interface is responsive and works on desktop and mobile, with session scoring so you can track wins and draws. No account or download is required—just open and play.

**Gameplay:** Two players take turns placing X and O on a 3×3 grid. The first to get three in a row (horizontally, vertically, or diagonally) wins. If the grid fills with no winner, the game is a draw. In single-player mode, you play against the computer, which uses a simple strategy to block and try to win. Reset the board anytime to start a new game; the score persists for the current session.

**Why it's here:** As a developer tool page, it demonstrates a small, self-contained game that runs entirely in the browser. It’s useful for testing UI patterns, local storage, or simple AI logic. Students and hobbyists can inspect the code to see how game state, turn handling, and win detection are implemented in a minimal setting.

**Technical note:** All logic and rendering run in your browser. No game state or moves are sent to any server. The AI uses a basic minimax-style approach for a quick, fun opponent. Enjoy the game, and use the "Back to Dashboard" link to explore other developer utilities on this site.`,
  },
};
